name: CI
on: [push]

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Run lint
#        run: ./gradlew lintDebug
#
#      - name: Upload lint report
#        uses: actions/upload-artifact@v2
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html

  unit-test: # tests in the test directory
#    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # local prperties isssue is fixed with this
      - name: Touch local properties
        run: touch local.properties

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # upload report as a file
      - name: Upload unit tests report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      # show report in the log
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

#  instrumentation-test: # tests in androidTest directory
#    needs: [unit-test]
#    runs-on: macos-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 11 for x64
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '11'
#
#      - name: Run espresso tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: instrumentation_test_report
#          path: app/build/reports/androidTests/connected/
